In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np  
import csv 
import datetime as dt

In [3]:
zillow_1 = pd.read_csv('./Resources/Zip_zhvi_bdrmcnt_1_uc_sfrcondo_tier_0.33_0.67_sm_sa_mon.csv')
zillow_1.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,1/31/1996,...,9/30/2019,10/31/2019,11/30/2019,12/31/2019,1/31/2020,2/29/2020,3/31/2020,4/30/2020,5/31/2020,6/30/2020
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,111258.0,...,717134,715191,712496,710656,709822,710312,711858,712502,712505,713185
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,111421.0,...,223303,222841,222420,222206,222280,222748,223201,223501,223454,223662
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,189781.0,...,825711,822467,819524,817030,816480,814888,813952,811516,810034,810253
3,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,128112.0,...,256844,256048,255162,254278,253906,254028,254544,255105,255632,256315
4,91940,5,77449,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,90479.0,...,143300,144023,143852,144365,144387,144938,145457,146069,146871,147265

In [4]:
df_1bdr=pd.melt(zillow_1,id_vars=['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       'State', 'City','Metro', 'CountyName']) 
df_1bdr.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,111258.0
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,111421.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,189781.0
3,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,128112.0
4,91940,5,77449,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1/31/1996,90479.0
5,61616,6,10002,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,NaN
6,91733,7,77084,Zip,TX,TX,Houston,Houston-The Woodlands-Sugar Land,Harris County,1/31/1996,NaN
7,93144,8,79936,Zip,TX,TX,El Paso,El Paso,El Paso County,1/31/1996,74403.0
8,84640,9,60640,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,62131.0
9,62037,10,11226,Zip,NY,NY,New York,New York-Newark-Jersey City,Kings County,1/31/1996,151024.0

In [5]:
df_1bdr["type"]="1-bdr"
df_1bdr["variable"]=df_1bdr["variable"].astype('datetime64[m]')
df_1bdr["epoch"] = (df_1bdr["variable"] - dt.datetime(1970,1,1)).dt.total_seconds()
df_1bdr=df_1bdr.dropna(how="any")
df_1bdr

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value,type,epoch
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1996-01-31,111258.0,1-bdr,8.230464e+08
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1996-01-31,111421.0,1-bdr,8.230464e+08
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1996-01-31,189781.0,1-bdr,8.230464e+08
3,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1996-01-31,128112.0,1-bdr,8.230464e+08
4,91940,5,77449,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1996-01-31,90479.0,1-bdr,8.230464e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5578645,93901,34322,82310,Zip,WY,WY,Lander,Riverton,Fremont County,2020-06-30,122681.0,1-bdr,1.593475e+09
5578646,60206,34322,6230,Zip,CT,CT,Pomfret Center,Worcester,Windham County,2020-06-30,171773.0,1-bdr,1.593475e+09
5578647,58952,34322,2872,Zip,RI,RI,Portsmouth,Providence-Warwick,Newport County,2020-06-30,204365.0,1-bdr,1.593475e+09
5578648,95186,34430,86343,Zip,AZ,AZ,Crown King,Prescott,Yavapai County,2020-06-30,118177.0,1-bdr,1.593475e+09
5578649,59376,34430,4109,Zip,ME,ME,Portland,Portland-South Portland,Cumberland County,2020-06-30,469468.0,1-bdr,1.593475e+09

In [6]:
schools_data= pd.read_csv('./Resources/number-of-schools.csv')
schools_data.head(10)

   index  objectid           city state    zip      county
0      0      2002     NEW SMYRNA    FL  32168     VOLUSIA
1      1      2003      WOODWORTH    LA  71485     RAPIDES
2      2      2004      BRUNSWICK    ME   4011  CUMBERLAND
3      3      2005       CARTHAGE    MS  39051       LEAKE
4      4      2006        KEARNEY    MO  64060        CLAY
5      5      2007        LINCOLN    NE  68516   LANCASTER
6      6      2008      LAS VEGAS    NV  89121       CLARK
7      7      2009      LAS VEGAS    NV  89141       CLARK
8      8      2010  ATLANTIC CITY    NJ   8401    ATLANTIC
9      9      2011      WESTFIELD    NJ   7090       UNION

In [9]:
nc_schols=schools_data[schools_data['state']=='NC']
nc_schols_df=nc_schols.groupby("zip")["objectid"].count().reset_index(name="count")
nc_df_1bdr=df_1bdr[df_1bdr['State']=='NC']
nc_df_1bdr.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value,type,epoch
718,69197,9434,27052,Zip,NC,NC,Walnut Cove,Winston-Salem,Stokes County,1996-01-31,61014.0,1-bdr,823046400.0
787,69206,1475,27103,Zip,NC,NC,Winston-Salem,Winston-Salem,Forsyth County,1996-01-31,60042.0,1-bdr,823046400.0
807,69209,651,27106,Zip,NC,NC,Winston-Salem,Winston-Salem,Forsyth County,1996-01-31,72332.0,1-bdr,823046400.0
860,69210,1059,27107,Zip,NC,NC,Winston-Salem,Winston-Salem,Forsyth County,1996-01-31,44889.0,1-bdr,823046400.0
878,69221,1660,27127,Zip,NC,NC,Winston-Salem,Winston-Salem,Forsyth County,1996-01-31,54674.0,1-bdr,823046400.0
883,69233,5590,27203,Zip,NC,NC,Asheboro,Greensboro-High Point,Randolph County,1996-01-31,84056.0,1-bdr,823046400.0
891,69235,3033,27205,Zip,NC,NC,Asheboro,Greensboro-High Point,Randolph County,1996-01-31,40790.0,1-bdr,823046400.0
1560,69268,5341,27263,Zip,NC,NC,Archdale,Greensboro-High Point,Randolph County,1996-01-31,62424.0,1-bdr,823046400.0
1561,69270,559,27265,Zip,NC,NC,High Point,Greensboro-High Point,Guilford County,1996-01-31,84129.0,1-bdr,823046400.0
1591,69273,6816,27282,Zip,NC,NC,High Point,Greensboro-High Point,Guilford County,1996-01-31,77471.0,1-bdr,823046400.0

In [10]:
nc_df_1bdr.to_csv('nc_1bed.csv', index=False, header=True)

In [11]:
zillow_3= pd.read_csv('./Resources/Zip_zhvi_bdrmcnt_3_uc_sfrcondo_tier_0.33_0.67_sm_sa_mon.csv')
zillow_3.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,1/31/1996,...,9/30/2019,10/31/2019,11/30/2019,12/31/2019,1/31/2020,2/29/2020,3/31/2020,4/30/2020,5/31/2020,6/30/2020
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,976021.0,...,1945737,1930647,1918358,1912831,1904208,1895108,1886062,1879163,1873173,1870230
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,257828.0,...,604460,602894,601747,600820,600775,601909,603650,604449,604373,604344
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,NaN,...,3248843,3247636,3244888,3226986,3218341,3211534,3215118,3205961,3206874,3206229
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,139236.0,...,255970,256194,256470,256662,256558,256533,256835,257802,258828,259490
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,320113.0,...,708596,707481,706163,704821,704312,703897,703822,702134,700427,698181

In [12]:
df_3bdr=pd.melt(zillow_3,id_vars=['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       'State', 'City','Metro', 'CountyName']) 
df_3bdr.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,976021.0
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,257828.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,NaN
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1/31/1996,139236.0
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,320113.0
5,91940,5,77449,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1/31/1996,89329.0
6,61616,6,10002,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,NaN
7,91733,7,77084,Zip,TX,TX,Houston,Houston-The Woodlands-Sugar Land,Harris County,1/31/1996,89148.0
8,93144,8,79936,Zip,TX,TX,El Paso,El Paso,El Paso County,1/31/1996,80521.0
9,84640,9,60640,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,202573.0

In [13]:
df_3bdr["type"]="3-bdr"
df_3bdr["variable"]=df_3bdr["variable"].astype('datetime64[m]')
df_3bdr["epoch"] = (df_3bdr["variable"] - dt.datetime(1970,1,1)).dt.total_seconds()
df_3bdr=df_3bdr.dropna(how="any")
df_3bdr

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value,type,epoch
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1996-01-31,976021.0,3-bdr,8.230464e+08
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1996-01-31,257828.0,3-bdr,8.230464e+08
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1996-01-31,139236.0,3-bdr,8.230464e+08
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1996-01-31,320113.0,3-bdr,8.230464e+08
5,91940,5,77449,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1996-01-31,89329.0,3-bdr,8.230464e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8491008,98400,34430,95721,Zip,CA,CA,Twin Bridges,Sacramento--Roseville--Arden-Arcade,El Dorado County,2020-06-30,314431.0,3-bdr,1.593475e+09
8491009,71534,34430,31421,Zip,GA,GA,Savannah,Savannah,Chatham County,2020-06-30,388518.0,3-bdr,1.593475e+09
8491011,69846,34430,28310,Zip,NC,NC,Fayetteville,Fayetteville,Cumberland County,2020-06-30,38536.0,3-bdr,1.593475e+09
8491012,77449,34430,45114,Zip,OH,OH,Wilmington,Wilmington,Clinton County,2020-06-30,101857.0,3-bdr,1.593475e+09
8491013,95186,34430,86343,Zip,AZ,AZ,Crown King,Prescott,Yavapai County,2020-06-30,215886.0,3-bdr,1.593475e+09

In [14]:
nc_schols=schools_data[schools_data['state']=='NC']
nc_schols_df=nc_schols.groupby("zip")["objectid"].count().reset_index(name="count")
nc_df_3bdr=df_3bdr[df_3bdr['State']=='NC']
nc_df_3bdr.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value,type,epoch
32,69816,33,28269,Zip,NC,NC,Charlotte,Charlotte-Concord-Gastonia,Mecklenburg County,1996-01-31,116625.0,3-bdr,823046400.0
55,69823,56,28277,Zip,NC,NC,Charlotte,Charlotte-Concord-Gastonia,Mecklenburg County,1996-01-31,154490.0,3-bdr,823046400.0
85,69672,86,28027,Zip,NC,NC,Concord,Charlotte-Concord-Gastonia,Cabarrus County,1996-01-31,123352.0,3-bdr,823046400.0
139,69431,140,27587,Zip,NC,NC,Wake Forest,Raleigh,Wake County,1996-01-31,155561.0,3-bdr,823046400.0
184,69699,186,28078,Zip,NC,NC,Huntersville,Charlotte-Concord-Gastonia,Mecklenburg County,1996-01-31,136982.0,3-bdr,823046400.0
189,69450,191,27610,Zip,NC,NC,Raleigh,Raleigh,Wake County,1996-01-31,118902.0,3-bdr,823046400.0
192,69340,194,27410,Zip,NC,NC,Greensboro,Greensboro-High Point,Guilford County,1996-01-31,128093.0,3-bdr,823046400.0
198,69336,200,27406,Zip,NC,NC,Greensboro,Greensboro-High Point,Guilford County,1996-01-31,92693.0,3-bdr,823046400.0
213,69849,215,28314,Zip,NC,NC,Fayetteville,Fayetteville,Cumberland County,1996-01-31,85603.0,3-bdr,823046400.0
319,69275,321,27284,Zip,NC,NC,Kernersville,Winston-Salem,Forsyth County,1996-01-31,107020.0,3-bdr,823046400.0

In [15]:
nc_df_3bdr.to_csv('nc_3bed.csv', index=False, header=True)

In [16]:
zillow_4= pd.read_csv('./Resources/Zip_zhvi_bdrmcnt_4_uc_sfrcondo_tier_0.33_0.67_sm_sa_mon.csv')
zillow_4.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,1/31/1996,...,9/30/2019,10/31/2019,11/30/2019,12/31/2019,1/31/2020,2/29/2020,3/31/2020,4/30/2020,5/31/2020,6/30/2020
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,NaN,...,3064324,3053163,3031928,3032413,3037638,3038871,3031707,3013141,3005806,3011777
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,398286.0,...,1007829,1007140,1005980,1004071,1002907,1002515,1002070,1000673,998107,995198
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,NaN,...,6418574,6453737,6476901,6488955,6440409,6386920,6323189,6289909,6238680,6221807
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,190908.0,...,335594,335558,335428,335402,335042,335201,335626,336623,337462,337961
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,515152.0,...,1251896,1249248,1246234,1243491,1242884,1245305,1247131,1247754,1245511,1245141

In [18]:
df_4bdr=pd.melt(zillow_4,id_vars=['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       'State', 'City','Metro', 'CountyName']) 
df_4bdr.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,NaN
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,398286.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,NaN
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1/31/1996,190908.0
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,515152.0
5,91940,5,77449,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1/31/1996,107388.0
6,61616,6,10002,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,1/31/1996,NaN
7,91733,7,77084,Zip,TX,TX,Houston,Houston-The Woodlands-Sugar Land,Harris County,1/31/1996,115424.0
8,93144,8,79936,Zip,TX,TX,El Paso,El Paso,El Paso County,1/31/1996,108152.0
9,84640,9,60640,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1/31/1996,250004.0

In [19]:
df_4bdr["type"]="4-bdr"
df_4bdr["variable"]=df_4bdr["variable"].astype('datetime64[m]')
df_4bdr["epoch"] = (df_4bdr["variable"] - dt.datetime(1970,1,1)).dt.total_seconds()
df_4bdr=df_4bdr.dropna(how="any")
df_4bdr

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value,type,epoch
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1996-01-31,398286.0,4-bdr,8.230464e+08
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1996-01-31,190908.0,4-bdr,8.230464e+08
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,1996-01-31,515152.0,4-bdr,8.230464e+08
5,91940,5,77449,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,1996-01-31,107388.0,4-bdr,8.230464e+08
7,91733,7,77084,Zip,TX,TX,Houston,Houston-The Woodlands-Sugar Land,Harris County,1996-01-31,115424.0,4-bdr,8.230464e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7870963,75095,34430,38959,Zip,MS,MS,Inverness,Indianola,Sunflower County,2020-06-30,40539.0,4-bdr,1.593475e+09
7870964,58866,34430,2714,Zip,MA,MA,Dartmouth,Providence-Warwick,Bristol County,2020-06-30,946942.0,4-bdr,1.593475e+09
7870965,95186,34430,86343,Zip,AZ,AZ,Crown King,Prescott,Yavapai County,2020-06-30,249801.0,4-bdr,1.593475e+09
7870966,66881,34430,21405,Zip,MD,MD,Annapolis,Baltimore-Columbia-Towson,Anne Arundel County,2020-06-30,910535.0,4-bdr,1.593475e+09
7870967,69440,34430,27599,Zip,NC,NC,Durham,Durham-Chapel Hill,Durham County,2020-06-30,287020.0,4-bdr,1.593475e+09

In [20]:
nc_schols=schools_data[schools_data['state']=='NC']
nc_schols_df=nc_schols.groupby("zip")["objectid"].count().reset_index(name="count")
nc_df_4bdr=df_4bdr[df_4bdr['State']=='NC']
nc_df_4bdr.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,variable,value,type,epoch
31,69816,33,28269,Zip,NC,NC,Charlotte,Charlotte-Concord-Gastonia,Mecklenburg County,1996-01-31,166563.0,4-bdr,823046400.0
54,69823,56,28277,Zip,NC,NC,Charlotte,Charlotte-Concord-Gastonia,Mecklenburg County,1996-01-31,232575.0,4-bdr,823046400.0
84,69672,86,28027,Zip,NC,NC,Concord,Charlotte-Concord-Gastonia,Cabarrus County,1996-01-31,178746.0,4-bdr,823046400.0
138,69431,140,27587,Zip,NC,NC,Wake Forest,Raleigh,Wake County,1996-01-31,265843.0,4-bdr,823046400.0
183,69699,186,28078,Zip,NC,NC,Huntersville,Charlotte-Concord-Gastonia,Mecklenburg County,1996-01-31,204852.0,4-bdr,823046400.0
188,69450,191,27610,Zip,NC,NC,Raleigh,Raleigh,Wake County,1996-01-31,132335.0,4-bdr,823046400.0
191,69340,194,27410,Zip,NC,NC,Greensboro,Greensboro-High Point,Guilford County,1996-01-31,177292.0,4-bdr,823046400.0
197,69336,200,27406,Zip,NC,NC,Greensboro,Greensboro-High Point,Guilford County,1996-01-31,130326.0,4-bdr,823046400.0
212,69849,215,28314,Zip,NC,NC,Fayetteville,Fayetteville,Cumberland County,1996-01-31,127457.0,4-bdr,823046400.0
318,69275,321,27284,Zip,NC,NC,Kernersville,Winston-Salem,Forsyth County,1996-01-31,164285.0,4-bdr,823046400.0

In [21]:
nc_df_4bdr.to_csv('nc_4bed.csv', index=False, header=True)